version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      actions-deps:
        patterns:
          - '@actions/*'
      types:
        patterns:
          - '@types/*'
      eslint:
        patterns:
          - '@redhat-actions/eslint-config'
          - '@typescript-eslint/*'
          - eslint

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
