repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.24.1
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        args: [--max-warnings=0]
        additional_dependencies:
          - eslint@8.50.0
          - typescript@5.2.2
          - '@typescript-eslint/eslint-plugin@6.7.3'
          - '@typescript-eslint/parser@6.7.3'
          - '@redhat-actions/eslint-config@1.3.2'

  - repo: local
    hooks:
      - id: compile
        name: compile
        language: system
        entry: npm run compile
        pass_filenames: false
        files: ^src/
