name: Check Case Normalization
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

env:
  IMAGE_NAME: ImageCaseTest
  IMAGE_TAGS: v1 TagCaseTest

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      action: ${{ steps.filter.outputs.action }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            action:
              - 'src/**'
              - 'dist/**'
              - 'action.yml'
              - 'package.json'
              - 'package-lock.json'
              - '.github/workflows/check-lowercase.yaml'

  build:
    name: Build image using Buildah
    needs: changes
    if: ${{ needs.changes.outputs.action == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        install_latest: [ true, false ]

    steps:

      - name: Checkout Buildah action
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: "buildah-build"

      - name: Install latest buildah
        if: matrix.install_latest
        run: |
          bash buildah-build/.github/install_latest_buildah.sh

      - name: Create Dockerfile
        run: |
          cat > Containerfile<<EOF
          FROM busybox
          RUN echo "hello world"
          EOF

      - name: Build Image
        id: build_image
        uses: ./buildah-build/
        with:
          image: ${{ env.IMAGE_NAME }}
          layers: false
          tags: ${{ env.IMAGE_TAGS }}
          containerfiles: |
            ./Containerfile
          extra-args: |
            --pull

      - name: Echo Outputs
        run: |
          echo "Image: ${{ steps.build_image.outputs.image }}"
          echo "Tags: ${{ steps.build_image.outputs.tags }}"
          echo "Tagged Image: ${{ steps.build_image.outputs.image-with-tag }}"
          echo "Image Digest: ${{ steps.build_image.outputs.digest }}"

      - name: Check images created
        run: buildah images
