name: CI checks
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: Lint, Check Bundle, Check I/O
    runs-on: ubuntu-24.04
    env:
      BUNDLE_FILE: "dist/index.js"
      BUNDLE_COMMAND: "npm run bundle"
      IO_FILE: ./src/generated/inputs-outputs.ts

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Verify Latest Bundle
        uses: aardbol-actions/common/bundle-verifier@a237273f41dc217821aff666362bd4aa739b18f9 # v2.0.1
        with:
          bundle_file: ${{ env.BUNDLE_FILE }}
          bundle_command: ${{ env.BUNDLE_COMMAND }}

      - name: Verify Input and Output enums
        uses: aardbol-actions/common/action-io-generator@a237273f41dc217821aff666362bd4aa739b18f9 # v2.0.1
        with:
          io_file: ${{ env.IO_FILE }}
