name: Scorecards supply-chain security
on:
  branch_protection_rule:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches: [main]

permissions: read-all

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      id-token: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Analyze
        uses: ossf/scorecard-action@ea651e62978af7915d09fe2e282747c798bf2dab # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@b0565cb28b456da32509aef995361ffcc63f40b0 # v3.28.15
        with:
          sarif_file: results.sarif
